name: Publish extension
on:
  push:
    tags:
      - "v*"

jobs:
  publish-extension:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Run npm install
        run: npm install

      - name: Run npm build
        run: npm run-script build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
              myorg/myrepository
          tags: |
            type=semver,pattern={{version}}
            type=sha
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: aquasec/trivy-docker-extension
          tags: aquasec/trivy-docker-extension:latest,aquasec/trivy-docker-extension:{{version}}